In [27]:
import pandas as pd
from IPython.display import display
f = pd.read_excel('employee_data.xlsx')
MonthlySalary = f ['Monthly Salary']
YearsAtCompany = f ['Years at Company']
JobSatisfaction = f ['Job Satisfaction']
CommuteTime = f ['Commute Time']
columns = ['Monthly Salary','Years at Company','Job Satisfaction','Commute Time']


# Calclation of min max scaling for the given columns
MinMax = f[columns].copy() 
MinMax = (MinMax - MinMax.min()) / (MinMax.max() - MinMax.min())
print ('Min Max scaling:')
display(MinMax)


# Calclation of Z-Score Normalization for the given columns
Z_score = f[columns].copy()
Z_score = (Z_score - Z_score.mean())/Z_score.std()
print ('Z-Score Normalization')
display(Z_score)

# Calclation of Robust Scaling for the given columns
Q1 = f[columns].quantile(0.25)
Q3 = f[columns].quantile(0.75)
IQR = Q3 - Q1
RobustScaling = f[columns].copy()
RobustScaling = (RobustScaling - RobustScaling.median())/IQR
print ('Robust Scaling:')
display(RobustScaling)

# Calclation of Decimal Scaling for the given columns
DecimalScaling = f[columns].copy()
max_value = f[columns].max()
k
for i:
    if max_value / 10 ^ i >= 1:
        i += 1
    else
        k = i - 1
RobustScaling = RobustScaling / 10 ** k

SyntaxError: invalid syntax (1313691089.py, line 37)

In [31]:
import pandas as pd
from IPython.display import display
f = pd.read_excel(r'D:\dataEngineer\excersise 8\employee_data.xlsx')
MonthlySalary = f ['Monthly Salary']
YearsAtCompany = f ['Years at Company']
JobSatisfaction = f ['Job Satisfaction']
CommuteTime = f ['Commute Time']
columns = ['Monthly Salary','Years at Company','Job Satisfaction','Commute Time']


# Calclation of min max scaling for the given columns
MinMax = f[columns].copy() 
MinMax = (MinMax - MinMax.min()) / (MinMax.max() - MinMax.min())
print ('Min Max scaling:')
display(MinMax)


# Calclation of Z-Score Normalization for the given columns
Z_score = f[columns].copy()
Z_score = (Z_score - Z_score.mean())/Z_score.std()
print ('Z-Score Normalization')
display(Z_score)

# Calclation of Robust Scaling for the given columns
Q1 = f[columns].quantile(0.25)
Q3 = f[columns].quantile(0.75)
IQR = Q3 - Q1
RobustScaling = f[columns].copy()
RobustScaling = (RobustScaling - RobustScaling.median())/IQR
print ('Robust Scaling:')
display(RobustScaling)

# Calclation of Decimal Scaling for the given columns
DecimalScaling = f[columns].copy()
max_value = DecimalScaling.abs().max()
k = {}
for column in columns:
    i = 0
    while max_value[column] / (10 ** i) >=1:
        i += 1
    k[column] = i

for column in columns:
    DecimalScaling[column] = DecimalScaling[column] / (10 ** k[column])
print ('Decimal Scaling:')
display(DecimalScaling)

# Calclation of log transformation for the given columns
import numpy as np
LogTransformation = f[columns].copy()
LogTransformation = np.log(LogTransformation)
print ("log transformation:")
display(LogTransformation)

Min Max scaling:

   Monthly Salary  Years at Company  Job Satisfaction  Commute Time
0        0.000000          0.000000          0.555556      0.100000
1        0.045977          0.111111          0.777778      0.166667
2        0.080460          0.222222          0.777778      0.233333
3        0.022989          0.111111          0.000000      0.666667
4        1.000000          1.000000          1.000000      0.000000
5        0.034483          0.111111          0.111111      0.833333
6        0.057471          0.222222          0.666667      0.266667
7        0.011494          0.000000          0.000000      1.000000
8        0.137931          0.444444          0.777778      0.333333
9        0.195402          0.444444          0.777778      0.166667

Z-Score Normalization

   Monthly Salary  Years at Company  Job Satisfaction  Commute Time
0       -0.525713         -0.883585          0.030166     -0.820884
1       -0.373332         -0.515425          0.633494     -0.623081
2       -0.259047         -0.147264          0.633494     -0.425277
3       -0.449522         -0.515425         -1.478152      0.860445
4        2.788563          2.429859          1.236821     -1.117589
5       -0.411427         -0.515425         -1.176489      1.354953
6       -0.335237         -0.147264          0.331830     -0.326376
7       -0.487618         -0.883585         -1.478152      1.849462
8       -0.068571          0.589057          0.633494     -0.128572
9        0.121904          0.589057          0.633494     -0.623081

Robust Scaling:

   Monthly Salary  Years at Company  Job Satisfaction  Commute Time
0       -0.529412              -0.6              -0.3         -0.36
1       -0.058824              -0.2               0.1         -0.20
2        0.294118               0.2               0.1         -0.04
3       -0.294118              -0.2              -1.3          1.00
4        9.705882               3.0               0.5         -0.60
5       -0.176471              -0.2              -1.1          1.40
6        0.058824               0.2              -0.1          0.04
7       -0.411765              -0.6              -1.3          1.80
8        0.882353               1.0               0.1          0.20
9        1.470588               1.0               0.1         -0.20

Decimal Scaling:

   Monthly Salary  Years at Company  Job Satisfaction  Commute Time
0           0.033              0.01              0.06          0.18
1           0.037              0.02              0.08          0.20
2           0.040              0.03              0.08          0.22
3           0.035              0.02              0.01          0.35
4           0.120              0.10              0.10          0.15
5           0.036              0.02              0.02          0.40
6           0.038              0.03              0.07          0.23
7           0.034              0.01              0.01          0.45
8           0.045              0.05              0.08          0.25
9           0.050              0.05              0.08          0.20

log transformation:

   Monthly Salary  Years at Company  Job Satisfaction  Commute Time
0        8.101678          0.000000          1.791759      2.890372
1        8.216088          0.693147          2.079442      2.995732
2        8.294050          1.098612          2.079442      3.091042
3        8.160518          0.693147          0.000000      3.555348
4        9.392662          2.302585          2.302585      2.708050
5        8.188689          0.693147          0.693147      3.688879
6        8.242756          1.098612          1.945910      3.135494
7        8.131531          0.000000          0.000000      3.806662
8        8.411833          1.609438          2.079442      3.218876
9        8.517193          1.609438          2.079442      2.995732